# Generated by Django 4.2.5 on 2024-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(verbose_name='Имя авторского аккаунта')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('gender', models.BooleanField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1, verbose_name='Пол')),
                ('self_esteem', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Уровень самооценки')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('age', models.IntegerField(editable=False, null=True, verbose_name='Возраст')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('status_rule', models.BooleanField(verbose_name='Согласие с правилами')),
                ('image', models.ImageField(upload_to='foto_profile', verbose_name='Фото профиля')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи в БД')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления записи в БД')),
            ],
        ),
    ]
