# Generated by Django 4.2.5 on 2024-03-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
